#!/bin/bash
#
###################################################################
# Peer to Peer Network - Jason D Stock - stock - October 08, 2019 #
###################################################################
#
# Run script for the Store application.
#
# Configurations

DIR="$( cd "$( dirname "$0" )" && pwd )"
JAR_PATH="$DIR/conf/:$DIR/build/libs/peer-to-peer-network.jar"
APPLICATION_PROPERTIES="$DIR/conf/application.properties"

# Launch Store
    
java -cp $JAR_PATH cs555.system.node.Store "$@"
